// All static user-facing strings (labels, placeholders, notes, and help text)
// live here so they are easy to find and change. No other module holds UI text.
export const UI_TEXT = {
  common: {
    by: "by ",
    unknown: "Unknown",
    cancel: "Cancel",
    close: "Close",
    listSeparator: ", ",
  },
  cover: {
    alt: (title: string) => `Cover of ${title}`,
    noCover: "No cover available",
  },
  app: {
    title: "Book Club",
    tagline: "Recommend and track books with friends. No login needed.",
    headerAlt: "Book Club header",
    footer: "Source code: ",
    github: "GitHub",
    dataSource: "Data provided by Open Library.",
    notConfigured: {
      prompt:
        "Supabase is not configured. Create a free project at supabase.com, run",
      schemaSql: "supabase/schema.sql",
      thenCopy: ", then copy",
      envExample: ".env.example",
      to: "to",
      envLocal: ".env.local",
      withCredentials: "with your project URL and anon key.",
    },
    errors: {
      failedToLoad: (message: string) => `Failed to load data: ${message}`,
      couldNotCreateUser: (message: string) =>
        `Could not create user: ${message}`,
      couldNotAddBook: (message: string) => `Could not add book: ${message}`,
      couldNotEditComment: (message: string) =>
        `Could not edit comment: ${message}`,
    },
  },
  user: {
    sectionAria: "User identification",
    addUser: "Add User",
    welcome: "Welcome,",
    searchPlaceholder: "Search users or type a new one...",
    login: "Login",
    signedInAs: "Signed in as",
    logout: "Logout",
    errors: {
      pickFirst: "Pick an existing user first.",
      invalidName:
        "Usernames: 1-40 chars, letters, numbers, emojis; spaces between words (no leading/trailing).",
      exists: "That user already exists - pick them from the list.",
    },
  },
  addBooks: {
    sectionAria: "Add books",
    hideAdding: "Hide adding books",
    startAdding: "Start adding books",
    searchPlaceholder: "Book title or ISBN...",
    clearSearchAria: "Clear search text",
    clearGlyph: "×",
    search: "Search",
    searching: "Searching...",
    clear: "Clear",
    noResults: "No results for that search.",
    searchFailed: "Book search failed. Try again.",
    commentPlaceholder: "Comment (optional)...",
    notThis: "Not This",
    add: "Add",
    recommended: "Recommended",
    confirm: "Confirm",
    ellipsis: "…",
    modal: {
      addingPrefix: "You are adding",
    },
  },
  list: {
    sectionAria: "Recommended books",
    sortLabel: "Sort:",
    sort: {
      rating: "Recommended Rating",
      recommendedCount: "Recommended Count",
      readCount: "Read Count",
      addedOldest: "Added (Oldest)",
      addedNewest: "Added (Newest)",
      commentsMost: "Comments (Most)",
      commentsLeast: "Comments (Least)",
      titleAsc: "Title (A-Z)",
      titleDesc: "Title (Z-A)",
    },
    filter: "Filter",
    collapseAll: "Collapse all",
    expandAll: "Expand all",
    emptyNote: "No books match. Add one above or clear filters.",
    recommendToggle: "Recommend",
    readToggle: "Read",
    stats: {
      recommended: (n: number) => `Recommended: ${n}`,
      read: (n: number) => `Read: ${n}`,
    },
    percentBadge: (p: number) => `${p}%`,
    percentBadgeTooltip: (p: number) => `${p}% of users recommends this book.`,
    commentsHeader: (count: number, collapsed: boolean) =>
      `Comments (${count}) ${collapsed ? "▸" : "▾"}`,
    edited: " (edited)",
    save: "Save",
    edit: "Edit",
    commentPlaceholder: "Add a comment...",
    commentSubmit: "Comment",
    selectUserNote: "Login to comment.",
    displayLabel: "Display:",
    displayInfinite: "Infinite",
    displaySize10: "10",
    displaySize50: "50",
    previous: "Previous",
    next: "Next",
    ellipsis: "…",
    paginationLabel: "Pagination",
    pageNumberAria: (n: number) => `Go to page ${n}`,
  },
  filter: {
    sectionAria: "Filter books",
    titleLabel: "Title",
    titlePlaceholder: "Title contains...",
    authorLabel: "Author",
    authorPlaceholder: "Author contains...",
    subjectLabel: "Subject",
    subjectPlaceholder: "Search subjects...",
    subjectResetGlyph: "○",
    subjectIncludeGlyph: "✓",
    subjectExcludeGlyph: "✕",
    subjectReset: "Reset",
    subjectInclude: "Include",
    subjectExclude: "Exclude",
    resetAll: "Reset filters",
  },
} as const;
